// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4PacVajiN-58qG5IwiGhZZcnamK_bKZg',
    appId: '1:272215548438:web:7ce828fe9f385aaeadcb37',
    messagingSenderId: '272215548438',
    projectId: 'parkinson-app-f2d24',
    authDomain: 'parkinson-app-f2d24.firebaseapp.com',
    storageBucket: 'parkinson-app-f2d24.appspot.com',
    measurementId: 'G-6109SMZMHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7OtwoPcri6gREhGUmzF_PIqwdxIALj7s',
    appId: '1:272215548438:android:a30681c56e7f5234adcb37',
    messagingSenderId: '272215548438',
    projectId: 'parkinson-app-f2d24',
    storageBucket: 'parkinson-app-f2d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYrprJNmxYzhdn2HS3p2Q0yLtuIQ0pPQg',
    appId: '1:272215548438:ios:34e3d9072ee088f3adcb37',
    messagingSenderId: '272215548438',
    projectId: 'parkinson-app-f2d24',
    storageBucket: 'parkinson-app-f2d24.appspot.com',
    iosBundleId: 'com.example.parkinson',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYrprJNmxYzhdn2HS3p2Q0yLtuIQ0pPQg',
    appId: '1:272215548438:ios:e4a3d77a4e7a5084adcb37',
    messagingSenderId: '272215548438',
    projectId: 'parkinson-app-f2d24',
    storageBucket: 'parkinson-app-f2d24.appspot.com',
    iosBundleId: 'com.example.parkinson.RunnerTests',
  );
}
